#### Homework Code

In [113]:
import numpy as np

In [114]:
a = np.matrix([[5, 6], [3, 7]])
b = np.matrix([[3,2], [1,5]])


Matrix Multiplication

In [115]:
a*b

matrix([[21, 40],
        [16, 41]])

In [116]:
b*a

matrix([[21, 32],
        [20, 41]])

In [117]:
Matrix Addition

SyntaxError: invalid syntax (<ipython-input-117-ccf2ecc7ed98>, line 1)

In [118]:
2*a

matrix([[10, 12],
        [ 6, 14]])

In [119]:
0.5*b

matrix([[ 1.5,  1. ],
        [ 0.5,  2.5]])

In [120]:
a + b

matrix([[ 8,  8],
        [ 4, 12]])

In [121]:
a -b

matrix([[2, 4],
        [2, 2]])

Quadratic Form a(t)* B * a

In [122]:
a = np.matrix([[2],[3]])

In [123]:
B = np.matrix([[1,2],[3,1]])

In [112]:
np.dot(a.T,B)*a

matrix([[43]])

Calculate Determinant 

In [134]:
A = np.matrix([[1,3,2,1],[4,0,5,0],[2,7,1,6],[0,1,4,10]])
A

matrix([[ 1,  3,  2,  1],
        [ 4,  0,  5,  0],
        [ 2,  7,  1,  6],
        [ 0,  1,  4, 10]])

In [135]:
round(np.linalg.det(A))

542.0

Calculate Inverse

In [136]:
A = np.matrix([[1,2,4],[1,3,7],[1,-1,-2]])

In [133]:
A

matrix([[ 1,  2,  4],
        [ 1,  3,  7],
        [ 1, -1, -2]])

In [144]:
np.linalg.inv(A)

matrix([[ 0.33333333,  0.        ,  0.66666667],
        [ 3.        , -2.        , -1.        ],
        [-1.33333333,  1.        ,  0.33333333]])